insert into books (book_id, title, author) values (1, 'Madame Curie', 'Tybi MacKessock');
insert into books (book_id, title, author) values (2, 'Triple Agent', 'Garth Belton');
insert into books (book_id, title, author) values (3, 'Life Without Dick', 'Farrand Taylerson');
insert into books (book_id, title, author) values (4, 'Saint John of Las Vegas', 'Terrence Barabich');
insert into books (book_id, title, author) values (5, 'Not Forgotten', 'Arnuad Retchless');
insert into books (book_id, title, author) values (6, 'Bonnie Scotland (Heroes of the Regiment)', 'Hernando De Roeck');
insert into books (book_id, title, author) values (7, 'Broken Wings (Knafayim Shvurot)', 'Edlin Kristoffersen');
insert into books (book_id, title, author) values (8, 'Sherlock Holmes', 'Julio Simoneton');
insert into books (book_id, title, author) values (9, 'Battlestar Galactica: Razor', 'Kayla Boutwell');
insert into books (book_id, title, author) values (10, 'Tru Confessions', 'Betta Tarbin');
insert into books (book_id, title, author) values (11, 'Birdwatchers', 'Andriette Burnhard');
insert into books (book_id, title, author) values (12, 'Love, Money, Love', 'Vernor Skelhorn');
insert into books (book_id, title, author) values (13, 'Mangler, The', 'Consuelo Cholmondeley');
insert into books (book_id, title, author) values (14, 'Brute (Bandyta)', 'Chen Hyam');
insert into books (book_id, title, author) values (15, 'Pelle the Conqueror (Pelle erobreren)', 'Murdock Cogle');
insert into books (book_id, title, author) values (16, 'Project X', 'Rick Schwand');
insert into books (book_id, title, author) values (17, 'Ex-Girlfriends', 'Daile Karolovsky');
insert into books (book_id, title, author) values (18, 'Time Walker (a.k.a. Being From Another Planet)', 'Ania Donaghie');
insert into books (book_id, title, author) values (19, 'From Justin to Kelly', 'Petronilla Bengle');
insert into books (book_id, title, author) values (20, 'Mutiny on the Bounty', 'Claus Wakerley');
insert into books (book_id, title, author) values (21, 'At the River I Stand', 'Valery Watsam');
insert into books (book_id, title, author) values (22, 'Our Man in Havana', 'Esra Shuttle');
insert into books (book_id, title, author) values (23, 'Horror Hotel (a.k.a. City of the Dead, The)', 'Lena Carp');
insert into books (book_id, title, author) values (24, 'Cure, The', 'Don Lukianov');
insert into books (book_id, title, author) values (25, 'Axed', 'Clerc Wilcher');
insert into books (book_id, title, author) values (26, 'Lovers, The (Les Amants)', 'Christy Delves');
insert into books (book_id, title, author) values (27, 'Blackballed: The Bobby Dukes Story', 'Gail Abramsky');
insert into books (book_id, title, author) values (28, 'Stay Hungry', 'Orson Rzehorz');
insert into books (book_id, title, author) values (29, 'Alphabet Killer, The', 'Susana Kleinber');
insert into books (book_id, title, author) values (30, 'Deception', 'Brande Bleackley');